DROP TABLE IF EXISTS booking_seats;
DROP TABLE IF EXISTS bookings;
DROP TABLE IF EXISTS show_seats;
DROP TABLE IF EXISTS shows;

CREATE TABLE shows (
                       id BIGINT PRIMARY KEY,
                       theatre_id BIGINT NOT NULL,
                       screen_id BIGINT NOT NULL,
                       movie_title VARCHAR(255) NOT NULL,
                       show_time TIMESTAMP NOT NULL
);

CREATE TABLE show_seats (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            show_id BIGINT NOT NULL,
                            seat_id BIGINT NOT NULL,
                            status VARCHAR(20) NOT NULL,
                            CONSTRAINT uk_show_seat UNIQUE (show_id, seat_id)
);

CREATE TABLE bookings (
                          id VARCHAR(64) PRIMARY KEY,
                          show_id BIGINT NOT NULL,
                          customer_name VARCHAR(255) NOT NULL,
                          customer_email VARCHAR(255) NOT NULL,
                          status VARCHAR(30) NOT NULL,
                          total_amount DOUBLE NOT NULL,
                          created_at TIMESTAMP NOT NULL
);

CREATE TABLE booking_seats (
                               id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               booking_id VARCHAR(64) NOT NULL,
                               show_seat_id BIGINT NOT NULL,
                               CONSTRAINT uk_booking_show_seat UNIQUE (show_seat_id)
);
